
x-uffizzi:
  ingress:
    service: loadbalancer
    port: 8080  
  continuous_previews:
    delete_preview_after: 1h

services:
  crm-frontend:
    image: "${FRONTEND_IMAGE}"
    volumes:
      - /app/node_modules
