# fly.toml app configuration file generated for crm-web-preprod on 2023-12-15T20:46:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crm-web-preprod"
primary_region = "jnb"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[env]
  NEXT_PUBLIC_API_URL = "https://crm-api.fly.dev"
  PORT = "3000"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
