import { NewUserFields } from "@/types";

export const API_URL = process.env.NEXT_PUBLIC_API_URL;

export const REGEXVALIDATION = {
  name: /^[a-zA-Z]+$/,
  email: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  password:
    /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/,
  phoneNumberSingle: /^[+]?[(]?[0-9]{3}[)]?[-\s.]?[0-9]{3}[-\s.]?[0-9]{4,6}$/,
  phoneNumberMultiple:
    /^(?:(?:[+]?[(]?[0-9]{3}[)]?[-\s.]?[0-9]{3}[-\s.]?[0-9]{4,6})(?:\/|$)){1,7}$/,
  twitter: /^(https?:\/\/)?(www\.)?twitter\.com\/[A-Za-z0-9_]{1,15}\/?$/,
  linkedIn:
    /^(https?:\/\/)?([a-z]{2,3}\.)?linkedin\.com\/(in|pub|company)\/[\w-]+\/?$/,
  shouldNotBeEmptyString: /^\s*\S.*\S\s*$/,
  listSeparatedByComma:
    /^(?=\s*[\w+#\s]*\S)[\w+#\s]+(?:\s*,\s*[\w+#\s]+)*,?\s*$/,
};

export let NEW_USER_DATA: NewUserFields = {
  first_name: "",
  last_name: "",
  password: "",
  password_confirmation: "",
  email: "",
  phone_number: "",
  stack: [],
  stack_id: 1,
  years_of_experience: null,
  bio: "",
  twitter_profile: "",
  linkedin_profile: "",
  github_profile: "",
  portfolio_url: "",
  is_active: false,
  profile_pic_url: "",
  skills: [],
  username: "",
  // tags: [],
};

// options from the contants-
const options = [
  { value: "react", label: "React" },
  { value: "vue", label: "Vue" },
  { value: "node", label: "Node" },
  { value: "express", label: "Express" },
  { value: "angular", label: "Angular" },
  { value: "svelte", label: "Svelte" },
  { value: "ember", label: "Ember.js" },
  { value: "backbone", label: "Backbone.js" },
  { value: "meteor", label: "Meteor" },
  { value: "express", label: "Express.js" },
  { value: "django", label: "Django" },
  { value: "flask", label: "Flask" },
  { value: "rails", label: "Ruby on Rails" },
  { value: "aspnet", label: "ASP.NET" },
  { value: "spring", label: "Spring" },
  { value: "laravel", label: "Laravel" },
  { value: "python", label: "Python" },
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "java", label: "Java" },
  { value: "cplus", label: "C++" },
  { value: "csharp", label: "C#" },
  { value: "ruby", label: "Ruby" },
  { value: "php", label: "PHP" },
  { value: "swift", label: "Swift" },
  { value: "go", label: "Go" },
  { value: "kotlin", label: "Kotlin" },
  { value: "r", label: "R" },
  { value: "objectivec", label: "Objective-C" },
  { value: "perl", label: "Perl" },
  { value: "haskell", label: "Haskell" },
  { value: "lua", label: "Lua" },
  { value: "rust", label: "Rust" },
  { value: "dart", label: "Dart" },
  { value: "mongodb", label: "MongoDB" },
  { value: "couchdb", label: "CouchDB" },
  { value: "redis", label: "Redis" },
  { value: "cassandra", label: "Cassandra" },
  { value: "dynamodb", label: "DynamoDB" },
  { value: "firebase", label: "Firebase Realtime Database" },
  { value: "mysql", label: "MySQL" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "sqlite", label: "SQLite" },
  { value: "sqlserver", label: "MS SQL Server" },
  { value: "aws", label: "AWS" },
  { value: "azure", label: "Azure" },
  { value: "gcp", label: "Google Cloud Platform" },
  { value: "ibmcloud", label: "IBM Cloud" },
  { value: "alibabacloud", label: "Alibaba Cloud" },
  { value: "heroku", label: "Heroku" },
  { value: "digitalocean", label: "DigitalOcean" },
  { value: "linode", label: "Linode" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "jenkins", label: "Jenkins" },
  { value: "gitlabci", label: "GitLab CI/CD" },
  { value: "travisci", label: "Travis CI" },
  { value: "circleci", label: "CircleCI" },
  { value: "terraform", label: "Terraform" },
  { value: "ansible", label: "Ansible" },
  { value: "puppet", label: "Puppet" },
  { value: "chef", label: "Chef" },
  { value: "graphql", label: "GraphQL" },
  { value: "rest", label: "REST APIs" },
  { value: "websockets", label: "WebSockets" },
  { value: "grpc", label: "gRPC" },
  { value: "solidity", label: "Solidity (Ethereum)" },
  { value: "blockchain", label: "Blockchain Technologies" },
];
export default options;
