name: fly deploy if app exists
on:
  push
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: echo "review-${GITHUB_REF_NAME//[^[:alnum:]]/-}" > ./app
        - run: echo "deploying to $(cat ./app) if it exists"
        - run: if flyctl status -a $(cat ./app); then flyctl deploy -a $(cat ./app) --remote-only; fi;