
name: destroy fly app
on:
  pull_request:
    types:
      - closed
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Install flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master
    
    - name: Destroy app
      run: |
        lowercase_ref=$(echo "${{ github.head_ref }}" | tr '[:upper:]' '[:lower:]')
        preview_app="preview-${lowercase_ref//[^[:alnum:]]/-}"
        echo "$preview_app" > ./app
        echo "destroying app $(cat ./app) for PR ${{ github.event.number }}"
        flyctl destroy --yes $(cat ./app)