
name: destroy fly app
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Install flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master
    - run: echo "review-${GITHUB_HEAD_REF//[^[:alnum:]]/-}" > ./app
    - run: echo "destroying app $(cat ./app) for PR ${{ github.event.number }}"
    - name: destroy review app
      run: flyctl destroy --yes $(cat ./app)