
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build -t crm:latest .
      
      - name: Display image size
        run: |
          docker image inspect crm:latest --format='{{.Size}}'