
name: create and deploy fly app
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
      contents: read
      pull-requests: write 
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  create-deploy:
    name: Create/Deploy app
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    
    - name: Install flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master
    
    - name: Create/Deploy app
      id: deploy
      run: |
        echo "review-${GITHUB_HEAD_REF//[^[:alnum:]]/-}" > ./app
        if flyctl status -a $(cat ./app); then 
          echo "Deploying to $(cat ./app)"
          flyctl deploy -a $(cat ./app) --remote-only
        else
          echo "Creating $(cat ./app)"
          flyctl apps create -o personal $(cat ./app)
          flyctl deploy -a $(cat ./app) --remote-only
        fi

    - name: Print output
      run: echo `${{ steps.deploy.outputs }}`

    # - name: Write PR with preview link
    #   uses: actions/github-script@v6
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     script: |
    #       const output = `${{ steps.deploy.outcome }}
    #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

    #       github.rest.issues.createComment({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: output
    #       })




